import {create} from 'zustand'
import {
    AgeData, AllClient,
    Client,
    ClientAddressBook,
    ClientNotVisit,
    ClientStatus, ClientStoppedVisiting,
    DistrictData, HistoryCount, HistorySessions, NewClient, PermanentClient,
    RegionData,
} from "@/type/client/client";

const clientStore = create<Client>((set) => ({
    isLoading: false,
    setIsLoading: (val: boolean) => set({isLoading: val}),
    isClientModal: false,
    setIsClientModal: (val: boolean) => set({isClientModal: val}),
    selectedClientList: [],
    setSelectedClientList: (val: any) => set({selectedClientList: val}),
    statusData: null,
    setStatusData: (val: ClientStatus | null) => set({statusData: val}),
    addressBookData: null,
    setAddressBookData: (val: ClientAddressBook[] | null) => set({addressBookData: val}),
    updateClientDef: {
        firstName: '',
        lastName: '',
        job: '',
        ageId: '',
        phoneNumber: '',
        gender: '',
        birthDate: '',
        districtId: '',
        regionId: '',
        attachmentId: '',
        clientPreferences: ''
    },
    updateClient: {
        firstName: '',
        lastName: '',
        job: '',
        ageId: '',
        phoneNumber: '',
        gender: '',
        birthDate: '',
        districtId: '',
        regionId: '',
        attachmentId: '',
        clientPreferences: ''
    },
    setUpdateClient: (val: any) => set({updateClient: val}),
    ageData: null,
    setAgeData: (val: AgeData[] | null) => set({ageData: val}),
    regionData: null,
    setRegionData: (val: RegionData[] | null) => set({regionData: val}),
    districtData: null,
    setDistrictData: (val: DistrictData[] | null) => set({districtData: val}),
    attachmentID: null,
    setAttachmentID: (val: null | string | any) => set({attachmentID: val}),
    allClientsList: null,
    setAllClients: (val: AllClient[] | null) => set({allClientsList: val}),
    clientNotVisit: null,
    setClientNotVisit: (val: null | ClientNotVisit[]) => set({clientNotVisit: val}),
    clientStoppedVisiting: null,
    setClientStoppedVisit: (val: null | ClientStoppedVisiting[]) => set({clientStoppedVisiting: val}),
    newClient: null,
    setNewClient: (val: null | NewClient[]) => set({newClient: val}),
    permanentClient: null,
    setPermanentClient: (val: null | PermanentClient[]) => set({permanentClient: val}),
    services: null,
    setServices: (val: any[] | null) => set({services: val}),
    historyCountData: null,
    setHistoryCountData: (val: HistoryCount | null) => set({historyCountData: val}),
    upcomingData: null,
    setUpcomingData: (val: HistorySessions[] | null) => set({upcomingData: val}),
    pastData: null,
    setPastData: (val: HistorySessions[] | null) => set({pastData: val}),
    canceledData: null,
    setCanceledData: (val: HistorySessions[] | null) => set({canceledData: val}),
    refreshing: false,
    setRefreshing: (val: boolean) => set({refreshing: val}),
    tariff: null,
    setTariff: (val: string | null) => set({tariff: val})
}))

export default clientStore